import type { Scenario } from "@/types";

const CHARACTER =
  "the same Korean child with short brown hair, wearing a light blue fluffy hooded jacket, ";

export const animalSchool: Scenario = {
  id: "animal-school",
  title: "동물 학교",
  description: "동물 친구들과 함께하는 첫 학교생활 이야기",
  category: "daily-life",
  educationMessage: "모두 잘하는 게 달라요. 서로의 다름을 존중하고 응원하면 함께 성장할 수 있어요.",
  targetAge: "4-7세",
  pageCount: 12,
  pages: [
    {
      pageNumber: 1,
      text: "오늘은 동물 학교 첫날! {childName}(이)는 두근두근 떨리는 마음으로 커다란 나무 학교 앞에 섰어요.",
      sceneDescription: "커다란 나무 학교 앞에 서 있는 설레는 장면",
      illustrationPrompt: CHARACTER + "standing in front of a large tree school building, nervous but excited, animal students in background, watercolor children's illustration",
      prompt: CHARACTER + "standing in front of a large tree school building, nervous but excited, animal students in background, watercolor children's illustration",
      emotion: "nervous",
    },
    {
      pageNumber: 2,
      text: "교실에 들어가니 곰 선생님이 반겨주었어요. '어서 와! 자리에 앉아봐.' 옆자리에는 여우, 토끼, 다람쥐가 앉아 있었어요.",
      sceneDescription: "곰 선생님과 동물 친구들이 있는 교실 장면",
      illustrationPrompt: CHARACTER + "entering a cozy classroom with a bear teacher and animal classmates (fox, rabbit, squirrel), welcoming atmosphere, watercolor children's book style",
      prompt: CHARACTER + "entering a cozy classroom with a bear teacher and animal classmates (fox, rabbit, squirrel), welcoming atmosphere, watercolor children's book style",
      emotion: "shy",
    },
    {
      pageNumber: 3,
      text: "첫 수업은 그림 그리기! 다람쥐 '도토리'가 엄청 잘 그렸어요. {childName}(이)는 조금 부러웠지만 열심히 그렸어요.",
      sceneDescription: "다람쥐의 그림을 부러워하면서 자기 그림을 그리는 장면",
      illustrationPrompt: CHARACTER + "painting at an easel alongside a talented squirrel student, trying hard, classroom art lesson, watercolor children's illustration",
      prompt: CHARACTER + "painting at an easel alongside a talented squirrel student, trying hard, classroom art lesson, watercolor children's illustration",
      emotion: "envious",
    },
    {
      pageNumber: 4,
      text: "점심시간에 토끼 '뭉치'가 김밥을 떨어뜨려 울었어요. {childName}(이)는 도시락을 반 나눠주었어요. '같이 먹자!'",
      sceneDescription: "울고 있는 토끼에게 도시락을 나눠주는 장면",
      illustrationPrompt: CHARACTER + "sharing lunch with a crying rabbit friend at a school lunch table, kind and caring expression, watercolor children's book illustration",
      prompt: CHARACTER + "sharing lunch with a crying rabbit friend at a school lunch table, kind and caring expression, watercolor children's book illustration",
      emotion: "kind",
    },
    {
      pageNumber: 5,
      text: "오후에는 달리기 시간! 여우 '바람이'가 제일 빨랐어요. {childName}(이)는 꼴찌였지만 끝까지 완주했어요.",
      sceneDescription: "달리기에서 꼴찌지만 포기하지 않고 달리는 장면",
      illustrationPrompt: CHARACTER + "running last in a race with animal students but smiling and not giving up, schoolyard track, watercolor children's illustration",
      prompt: CHARACTER + "running last in a race with animal students but smiling and not giving up, schoolyard track, watercolor children's illustration",
      emotion: "determined",
    },
    {
      pageNumber: 6,
      text: "곰 선생님이 박수를 치며 말했어요. '끝까지 달린 게 제일 멋져! 모두 잘하는 게 다른 거야.'",
      sceneDescription: "곰 선생님이 칭찬해주는 따뜻한 장면",
      illustrationPrompt: CHARACTER + "receiving applause from a bear teacher and animal classmates after finishing a race, encouraging atmosphere, watercolor children's illustration",
      prompt: CHARACTER + "receiving applause from a bear teacher and animal classmates after finishing a race, encouraging atmosphere, watercolor children's illustration",
      emotion: "encouraged",
    },
    {
      pageNumber: 7,
      text: "다음은 노래 수업이에요. {childName}(이)가 노래를 부르자 모두가 귀를 쫑긋 세웠어요. '와, 진짜 잘한다!'",
      sceneDescription: "노래를 불러 동물 친구들을 감동시키는 장면",
      illustrationPrompt: CHARACTER + "singing beautifully in music class with animal students listening in awe, musical notes floating, watercolor children's book illustration",
      prompt: CHARACTER + "singing beautifully in music class with animal students listening in awe, musical notes floating, watercolor children's book illustration",
      emotion: "confident",
    },
    {
      pageNumber: 8,
      text: "방과 후 다람쥐 도토리가 다가왔어요. '나 노래 못하는데… 가르쳐줄 수 있어?' '{childName}(이)가 환하게 웃었어요. '그럼! 나도 그림 가르쳐줘!'",
      sceneDescription: "다람쥐와 서로의 장기를 교환하기로 하는 장면",
      illustrationPrompt: CHARACTER + "shaking hands with a squirrel classmate after school, both smiling, friendship forming, watercolor children's illustration",
      prompt: CHARACTER + "shaking hands with a squirrel classmate after school, both smiling, friendship forming, watercolor children's illustration",
      emotion: "friendly",
    },
    {
      pageNumber: 9,
      text: "매일매일 도토리에게 노래를 가르쳐주고, 도토리에게 그림을 배웠어요. 둘 다 점점 실력이 늘었어요!",
      sceneDescription: "서로 가르치고 배우며 성장하는 몽타주 장면",
      illustrationPrompt: CHARACTER + "teaching a squirrel to sing while squirrel teaches painting, split scene showing both activities, watercolor children's book illustration",
      prompt: CHARACTER + "teaching a squirrel to sing while squirrel teaches painting, split scene showing both activities, watercolor children's book illustration",
      emotion: "growing",
    },
    {
      pageNumber: 10,
      text: "발표회 날이 왔어요! {childName}(이)와 도토리가 함께 노래하며 그림을 그리는 공연을 했어요.",
      sceneDescription: "발표회에서 함께 공연하는 장면",
      illustrationPrompt: CHARACTER + "performing on stage with a squirrel friend, singing and painting together, audience of animal students cheering, watercolor children's illustration",
      prompt: CHARACTER + "performing on stage with a squirrel friend, singing and painting together, audience of animal students cheering, watercolor children's illustration",
      emotion: "proud",
    },
    {
      pageNumber: 11,
      text: "모든 동물 친구들이 박수를 보내주었어요. 곰 선생님의 눈에도 눈물이 고였어요. '이게 바로 우정이야!'",
      sceneDescription: "관객 모두가 감동받아 박수치는 장면",
      illustrationPrompt: CHARACTER + "bowing on stage with squirrel friend while bear teacher and animal students give standing ovation, warm watercolor children's illustration",
      prompt: CHARACTER + "bowing on stage with squirrel friend while bear teacher and animal students give standing ovation, warm watercolor children's illustration",
      emotion: "moved",
    },
    {
      pageNumber: 12,
      text: "집으로 돌아오는 길, {childName}(이)는 생각했어요. '학교 진짜 좋다! 내일도 빨리 가고 싶어!' 주머니 속 도토리의 그림 편지가 따뜻했어요.",
      sceneDescription: "학교에서 돌아오며 행복해하는 마무리 장면",
      illustrationPrompt: CHARACTER + "walking home from school happily holding a drawing letter, autumn leaves falling, warm watercolor children's book ending illustration",
      prompt: CHARACTER + "walking home from school happily holding a drawing letter, autumn leaves falling, warm watercolor children's book ending illustration",
      emotion: "happy",
    },
  ],
};
