import type { Scenario } from "@/types";

const CHARACTER =
  "the same Korean child with short brown hair, wearing a light blue fluffy hooded jacket, ";

export const dinosaurWorld: Scenario = {
  id: "dinosaur-world",
  title: "공룡 나라",
  description: "타임머신을 타고 떠나는 공룡 시대 대모험",
  category: "science",
  educationMessage: "크고 무서워 보여도 마음은 따뜻할 수 있어요. 겉모습만으로 판단하지 않아요.",
  targetAge: "4-8세",
  pageCount: 12,
  pages: [
    {
      pageNumber: 1,
      text: "{childName}(이)는 박물관에서 신기한 공룡 알을 발견했어요. 알에서 따스한 빛이 새어나오고 있었지요.",
      sceneDescription: "박물관에서 빛나는 공룡 알을 발견하는 장면",
      illustrationPrompt: CHARACTER + "discovering a glowing dinosaur egg in a museum, warm light emanating from the egg, watercolor children's book illustration",
      prompt: CHARACTER + "discovering a glowing dinosaur egg in a museum, warm light emanating from the egg, watercolor children's book illustration",
      emotion: "curious",
    },
    {
      pageNumber: 2,
      text: "알을 살짝 만지자 눈부신 빛이 번쩍! 정신을 차려보니 초록 숲이 끝없이 펼쳐진 공룡 시대였어요!",
      sceneDescription: "시간 이동 후 공룡 시대 풍경을 마주하는 장면",
      illustrationPrompt: CHARACTER + "standing in a prehistoric jungle landscape with ferns and volcanoes in background, amazed expression, watercolor children's illustration",
      prompt: CHARACTER + "standing in a prehistoric jungle landscape with ferns and volcanoes in background, amazed expression, watercolor children's illustration",
      emotion: "amazed",
    },
    {
      pageNumber: 3,
      text: "풀숲에서 작은 아기 트리케라톱스가 나왔어요. 엄마를 잃어버린 것 같아 눈이 촉촉했지요. '울지 마, 내가 도와줄게!'",
      sceneDescription: "울고 있는 아기 트리케라톱스를 달래는 장면",
      illustrationPrompt: CHARACTER + "comforting a small crying baby triceratops in a prehistoric jungle, gentle and caring, watercolor children's book style",
      prompt: CHARACTER + "comforting a small crying baby triceratops in a prehistoric jungle, gentle and caring, watercolor children's book style",
      emotion: "compassionate",
    },
    {
      pageNumber: 4,
      text: "아기 공룡과 함께 엄마를 찾아 나섰어요. 하늘에서 큰 프테라노돈이 날갯짓하며 길을 알려주었어요.",
      sceneDescription: "프테라노돈의 안내를 받으며 걷는 장면",
      illustrationPrompt: CHARACTER + "walking with a baby triceratops following a flying pteranodon overhead, prehistoric landscape, watercolor children's illustration",
      prompt: CHARACTER + "walking with a baby triceratops following a flying pteranodon overhead, prehistoric landscape, watercolor children's illustration",
      emotion: "determined",
    },
    {
      pageNumber: 5,
      text: "강가에 도착하니 목이 아주 긴 브라키오사우루스가 물을 마시고 있었어요. '엄마 트리케라톱스? 저 언덕 너머에서 봤어!'",
      sceneDescription: "거대한 브라키오사우루스에게 길을 묻는 장면",
      illustrationPrompt: CHARACTER + "looking up at a giant brachiosaurus by a river with a baby triceratops, prehistoric scene, watercolor children's book illustration",
      prompt: CHARACTER + "looking up at a giant brachiosaurus by a river with a baby triceratops, prehistoric scene, watercolor children's book illustration",
      emotion: "hopeful",
    },
    {
      pageNumber: 6,
      text: "언덕을 올라가는 길에 땅이 쿵쿵 울렸어요. 커다란 티렉스가 나타났거든요! 하지만 티렉스는 재채기만 하고 있었어요. '에취! 코에 꽃가루가…'",
      sceneDescription: "재채기하는 티렉스를 만나는 유머러스한 장면",
      illustrationPrompt: CHARACTER + "facing a large T-Rex that is sneezing comically with flowers around, baby triceratops hiding behind the child, funny watercolor children's illustration",
      prompt: CHARACTER + "facing a large T-Rex that is sneezing comically with flowers around, baby triceratops hiding behind the child, funny watercolor children's illustration",
      emotion: "surprised",
    },
    {
      pageNumber: 7,
      text: "{childName}(이)가 큰 나뭇잎으로 티렉스의 코를 닦아주었어요. '고마워! 무서웠지? 사실 난 꽃을 좋아해서 재채기를 달고 살아.'",
      sceneDescription: "티렉스의 코를 닦아주는 따뜻한 장면",
      illustrationPrompt: CHARACTER + "wiping a friendly T-Rex nose with a large leaf, both smiling, heartwarming watercolor children's illustration",
      prompt: CHARACTER + "wiping a friendly T-Rex nose with a large leaf, both smiling, heartwarming watercolor children's illustration",
      emotion: "kind",
    },
    {
      pageNumber: 8,
      text: "티렉스가 등에 태워주었어요! 세상에서 제일 높은 곳에서 보니 공룡 나라가 한눈에 보였어요.",
      sceneDescription: "티렉스 등에 올라타 공룡 세계를 내려다보는 장면",
      illustrationPrompt: CHARACTER + "riding on a T-Rex back overlooking a vast prehistoric landscape, baby triceratops sitting behind, adventurous watercolor illustration",
      prompt: CHARACTER + "riding on a T-Rex back overlooking a vast prehistoric landscape, baby triceratops sitting behind, adventurous watercolor illustration",
      emotion: "thrilled",
    },
    {
      pageNumber: 9,
      text: "저 멀리 언덕 아래에서 엄마 트리케라톱스가 아기를 찾아 두리번거리고 있었어요! '저기다!'",
      sceneDescription: "멀리서 엄마 트리케라톱스를 발견하는 장면",
      illustrationPrompt: CHARACTER + "pointing excitedly from atop a T-Rex at a mother triceratops in the distance, joyful discovery, watercolor children's illustration",
      prompt: CHARACTER + "pointing excitedly from atop a T-Rex at a mother triceratops in the distance, joyful discovery, watercolor children's illustration",
      emotion: "excited",
    },
    {
      pageNumber: 10,
      text: "아기 트리케라톱스가 엄마에게 달려갔어요. 엄마가 아기의 볼을 비비며 기뻐했어요. {childName}(이)도 눈물이 핑 돌았어요.",
      sceneDescription: "엄마와 아기 트리케라톱스의 감동적인 재회 장면",
      illustrationPrompt: CHARACTER + "watching a baby triceratops reuniting with its mother, emotional scene with tears of joy, warm watercolor children's book illustration",
      prompt: CHARACTER + "watching a baby triceratops reuniting with its mother, emotional scene with tears of joy, warm watercolor children's book illustration",
      emotion: "touched",
    },
    {
      pageNumber: 11,
      text: "엄마 트리케라톱스가 뿔에 걸린 목걸이를 건네주었어요. 공룡 발자국 모양 펜던트가 달려 있었지요. '고마워, 작은 영웅!'",
      sceneDescription: "엄마 트리케라톱스에게 감사 선물을 받는 장면",
      illustrationPrompt: CHARACTER + "receiving a necklace with dinosaur footprint pendant from a mother triceratops, grateful scene, watercolor children's illustration",
      prompt: CHARACTER + "receiving a necklace with dinosaur footprint pendant from a mother triceratops, grateful scene, watercolor children's illustration",
      emotion: "proud",
    },
    {
      pageNumber: 12,
      text: "공룡 알이 다시 빛나더니 {childName}(이)는 박물관으로 돌아왔어요. 손에는 공룡 발자국 목걸이가! 가장 멋진 모험이었어요!",
      sceneDescription: "박물관으로 돌아와 목걸이를 쥔 채 미소짓는 마무리 장면",
      illustrationPrompt: CHARACTER + "back in the museum holding a dinosaur footprint necklace, happy smile, warm watercolor children's book ending illustration",
      prompt: CHARACTER + "back in the museum holding a dinosaur footprint necklace, happy smile, warm watercolor children's book ending illustration",
      emotion: "happy",
    },
  ],
};
