import type { Scenario } from "@/types";

const CHARACTER =
  "the same Korean child with short brown hair, wearing a light blue fluffy hooded jacket, ";

export const fairyKingdom: Scenario = {
  id: "fairy-kingdom",
  title: "요정 왕국",
  description: "꽃잎 요정들과 함께 마법의 왕국을 구하는 판타지 이야기",
  category: "fantasy",
  educationMessage: "작은 친절이 세상을 밝게 만들어요. 누구나 특별한 능력을 가지고 있어요.",
  targetAge: "3-7세",
  pageCount: 12,
  pages: [
    {
      pageNumber: 1,
      text: "{childName}(이)는 정원에서 아주 작은 문을 발견했어요. 나뭇잎만 한 문에서 은은한 빛이 새어나왔지요.",
      sceneDescription: "정원 구석에서 작은 요정 문을 발견하는 장면",
      illustrationPrompt: CHARACTER + "discovering a tiny glowing fairy door at the base of a tree in a garden, magical light, watercolor children's book illustration",
      prompt: CHARACTER + "discovering a tiny glowing fairy door at the base of a tree in a garden, magical light, watercolor children's book illustration",
      emotion: "curious",
    },
    {
      pageNumber: 2,
      text: "문을 살짝 두드리자 몸이 슈우웅 작아졌어요! 눈앞에 반짝이는 꽃잎 마을이 펼쳐졌어요.",
      sceneDescription: "작아진 아이가 꽃잎 요정 마을을 보는 장면",
      illustrationPrompt: CHARACTER + "shrunk to tiny size standing at entrance of a fairy village made of flower petals, magical and whimsical, watercolor children's illustration",
      prompt: CHARACTER + "shrunk to tiny size standing at entrance of a fairy village made of flower petals, magical and whimsical, watercolor children's illustration",
      emotion: "amazed",
    },
    {
      pageNumber: 3,
      text: "장미꽃 요정 '로지'가 날아왔어요. '큰일이야! 무지개 샘물이 말라버려서 요정 왕국에 색이 사라지고 있어!'",
      sceneDescription: "걱정하는 장미꽃 요정 로지를 만나는 장면",
      illustrationPrompt: CHARACTER + "meeting a worried rose petal fairy with pink wings, fading colors in background, watercolor children's book style",
      prompt: CHARACTER + "meeting a worried rose petal fairy with pink wings, fading colors in background, watercolor children's book style",
      emotion: "concerned",
    },
    {
      pageNumber: 4,
      text: "'내가 도와줄게!' {childName}(이)가 말하자 로지의 얼굴이 환해졌어요. 함께 무지개 샘을 찾아 떠났어요.",
      sceneDescription: "로지와 함께 무지개 샘을 찾아 출발하는 장면",
      illustrationPrompt: CHARACTER + "walking with a rose fairy through a magical fairy kingdom, determined expression, colorful watercolor children's illustration",
      prompt: CHARACTER + "walking with a rose fairy through a magical fairy kingdom, determined expression, colorful watercolor children's illustration",
      emotion: "determined",
    },
    {
      pageNumber: 5,
      text: "은빛 나비들이 길을 안내해 주었어요. 이슬방울 다리를 건너고, 민들레 솜 구름 위를 걸었어요.",
      sceneDescription: "이슬방울 다리와 민들레 솜 구름 위를 걷는 환상적인 장면",
      illustrationPrompt: CHARACTER + "walking on dewdrop bridges and dandelion puff clouds guided by silver butterflies, dreamy fairy world, watercolor illustration",
      prompt: CHARACTER + "walking on dewdrop bridges and dandelion puff clouds guided by silver butterflies, dreamy fairy world, watercolor illustration",
      emotion: "wonder",
    },
    {
      pageNumber: 6,
      text: "무지개 샘에 도착했지만 큰 바위가 샘을 막고 있었어요! 혼자 힘으로는 꿈쩍도 안 했어요.",
      sceneDescription: "큰 바위에 막힌 무지개 샘 앞에 서 있는 장면",
      illustrationPrompt: CHARACTER + "standing before a large boulder blocking a rainbow spring, looking up at it with determination, fairy world watercolor illustration",
      prompt: CHARACTER + "standing before a large boulder blocking a rainbow spring, looking up at it with determination, fairy world watercolor illustration",
      emotion: "challenged",
    },
    {
      pageNumber: 7,
      text: "그때 {childName}(이)가 노래를 부르기 시작했어요. 다정한 노랫소리에 요정들이 하나둘 모여들었어요.",
      sceneDescription: "노래를 부르자 여러 요정들이 모여드는 장면",
      illustrationPrompt: CHARACTER + "singing while various flower fairies gather around, musical notes floating in air, magical watercolor children's book illustration",
      prompt: CHARACTER + "singing while various flower fairies gather around, musical notes floating in air, magical watercolor children's book illustration",
      emotion: "hopeful",
    },
    {
      pageNumber: 8,
      text: "요정들이 모두 함께 마법의 가루를 뿌렸어요. 반짝반짝! 바위가 서서히 꽃으로 변했어요!",
      sceneDescription: "요정들과 함께 마법으로 바위를 꽃으로 변화시키는 장면",
      illustrationPrompt: CHARACTER + "surrounded by fairies sprinkling magic dust on a boulder transforming into flowers, spectacular magical scene, watercolor illustration",
      prompt: CHARACTER + "surrounded by fairies sprinkling magic dust on a boulder transforming into flowers, spectacular magical scene, watercolor illustration",
      emotion: "excited",
    },
    {
      pageNumber: 9,
      text: "무지개 샘물이 다시 솟아올랐어요! 일곱 빛깔 물줄기가 하늘 높이 치솟으며 요정 왕국에 색을 돌려주었어요.",
      sceneDescription: "무지개 샘물이 솟구치며 왕국에 색이 돌아오는 장면",
      illustrationPrompt: CHARACTER + "watching a rainbow fountain burst upward restoring colors to the fairy kingdom, spectacular and joyful, watercolor children's illustration",
      prompt: CHARACTER + "watching a rainbow fountain burst upward restoring colors to the fairy kingdom, spectacular and joyful, watercolor children's illustration",
      emotion: "joyful",
    },
    {
      pageNumber: 10,
      text: "요정 여왕님이 직접 찾아왔어요. '고마워, 용감한 친구야. 네 따뜻한 마음이 기적을 만들었어.'",
      sceneDescription: "요정 여왕이 감사를 표하는 장면",
      illustrationPrompt: CHARACTER + "meeting a beautiful fairy queen with a crown of flowers, royal fairy court background, elegant watercolor children's illustration",
      prompt: CHARACTER + "meeting a beautiful fairy queen with a crown of flowers, royal fairy court background, elegant watercolor children's illustration",
      emotion: "honored",
    },
    {
      pageNumber: 11,
      text: "여왕님이 꽃잎으로 만든 왕관을 씌워주었어요. 이마에서 따스한 빛이 났어요. '넌 요정 왕국의 영원한 친구야!'",
      sceneDescription: "꽃잎 왕관을 받는 감동적인 장면",
      illustrationPrompt: CHARACTER + "being crowned with a flower petal tiara by a fairy queen, glowing warmly, watercolor children's book illustration",
      prompt: CHARACTER + "being crowned with a flower petal tiara by a fairy queen, glowing warmly, watercolor children's book illustration",
      emotion: "touched",
    },
    {
      pageNumber: 12,
      text: "다시 원래 크기로 돌아온 {childName}(이)는 정원에서 미소지었어요. 바람이 살랑 불 때마다 요정들의 웃음소리가 들리는 것 같았어요.",
      sceneDescription: "정원에서 바람소리에 요정들의 웃음을 느끼는 마무리 장면",
      illustrationPrompt: CHARACTER + "back to normal size in the garden smiling with sparkles in the breeze, warm sunset, watercolor children's book ending illustration",
      prompt: CHARACTER + "back to normal size in the garden smiling with sparkles in the breeze, warm sunset, watercolor children's book ending illustration",
      emotion: "content",
    },
  ],
};
