import type { Scenario } from "@/types";

const CHARACTER =
  "the same Korean child with short brown hair, wearing a light blue fluffy hooded jacket, ";

export const musicLand: Scenario = {
  id: "music-land",
  title: "음악의 나라",
  description: "악기 친구들과 함께 하모니를 만드는 음악 여행",
  category: "education",
  educationMessage: "혼자보다 함께하면 더 아름다운 소리를 만들 수 있어요. 조화와 협력이 중요해요.",
  targetAge: "3-7세",
  pageCount: 12,
  pages: [
    {
      pageNumber: 1,
      text: "{childName}(이)는 다락방에서 오래된 오르골을 발견했어요. 뚜껑을 열자 아름다운 멜로디와 함께 빛이 쏟아졌어요.",
      sceneDescription: "다락방에서 빛나는 오르골을 여는 장면",
      illustrationPrompt: CHARACTER + "opening a glowing music box in an attic, beautiful light and musical notes streaming out, watercolor children's book illustration",
      prompt: CHARACTER + "opening a glowing music box in an attic, beautiful light and musical notes streaming out, watercolor children's book illustration",
      emotion: "curious",
    },
    {
      pageNumber: 2,
      text: "빛 속으로 빨려 들어가니 악기들이 살아 움직이는 음악의 나라였어요! 음표 길이 반짝이며 이어져 있었지요.",
      sceneDescription: "음표로 된 길과 살아있는 악기가 있는 음악의 나라",
      illustrationPrompt: CHARACTER + "standing in a magical land made of music with paths of musical notes, living instruments walking around, colorful watercolor children's illustration",
      prompt: CHARACTER + "standing in a magical land made of music with paths of musical notes, living instruments walking around, colorful watercolor children's illustration",
      emotion: "amazed",
    },
    {
      pageNumber: 3,
      text: "작은 피아노 '또레미'가 슬픈 얼굴로 다가왔어요. '음악회가 내일인데, 악기들이 싸워서 연습을 안 해!'",
      sceneDescription: "슬픈 표정의 피아노 캐릭터를 만나는 장면",
      illustrationPrompt: CHARACTER + "meeting a sad small piano character with a worried face, musical land background, watercolor children's book style",
      prompt: CHARACTER + "meeting a sad small piano character with a worried face, musical land background, watercolor children's book style",
      emotion: "concerned",
    },
    {
      pageNumber: 4,
      text: "드럼 '둥둥이'는 너무 시끄럽다고 놀림받아 화가 나 있었어요. {childName}(이)가 말했어요. '둥둥이의 소리 없으면 음악이 재미없지!'",
      sceneDescription: "화난 드럼을 달래며 격려하는 장면",
      illustrationPrompt: CHARACTER + "encouraging an angry drum character, comforting and kind expression, musical instruments in background, watercolor children's illustration",
      prompt: CHARACTER + "encouraging an angry drum character, comforting and kind expression, musical instruments in background, watercolor children's illustration",
      emotion: "empathetic",
    },
    {
      pageNumber: 5,
      text: "바이올린 '비올라'는 혼자가 더 좋다며 구석에 앉아 있었어요. '같이 하면 더 예쁜 소리가 나는데!'",
      sceneDescription: "구석에 혼자 있는 바이올린을 설득하는 장면",
      illustrationPrompt: CHARACTER + "talking to a shy violin character sitting alone in a corner, persuading gently, watercolor children's book illustration",
      prompt: CHARACTER + "talking to a shy violin character sitting alone in a corner, persuading gently, watercolor children's book illustration",
      emotion: "patient",
    },
    {
      pageNumber: 6,
      text: "{childName}(이)가 제안했어요. '각자 한 소절씩 연주하고, 마지막에 다 같이 해보자!' 악기 친구들이 고개를 끄덕였어요.",
      sceneDescription: "악기들을 모아 연습 계획을 설명하는 장면",
      illustrationPrompt: CHARACTER + "standing in front of instrument characters explaining a plan with a conductor's baton, determined expression, watercolor children's illustration",
      prompt: CHARACTER + "standing in front of instrument characters explaining a plan with a conductor's baton, determined expression, watercolor children's illustration",
      emotion: "determined",
    },
    {
      pageNumber: 7,
      text: "둥둥이가 먼저 두둥! 리듬을 시작하자 모두의 발이 저절로 움직였어요. '역시 둥둥이야!'",
      sceneDescription: "드럼이 리듬을 치자 모두가 흥겨워하는 장면",
      illustrationPrompt: CHARACTER + "dancing to a drum's rhythm while other instrument characters tap their feet, lively and fun, watercolor children's book illustration",
      prompt: CHARACTER + "dancing to a drum's rhythm while other instrument characters tap their feet, lively and fun, watercolor children's book illustration",
      emotion: "joyful",
    },
    {
      pageNumber: 8,
      text: "비올라가 조심조심 활을 그었어요. 부드러운 멜로디에 모두가 귀를 기울였어요. '너무 아름다워!'",
      sceneDescription: "바이올린이 아름다운 선율을 연주하는 감동 장면",
      illustrationPrompt: CHARACTER + "listening with closed eyes as a violin character plays beautifully, musical notes floating, serene watercolor children's illustration",
      prompt: CHARACTER + "listening with closed eyes as a violin character plays beautifully, musical notes floating, serene watercolor children's illustration",
      emotion: "moved",
    },
    {
      pageNumber: 9,
      text: "드디어 모두 함께 연주했어요! 각자의 소리가 하나로 합쳐지자 하늘에 무지개 음표가 피어올랐어요!",
      sceneDescription: "모든 악기가 합주하며 무지개 음표가 피어오르는 클라이맥스",
      illustrationPrompt: CHARACTER + "conducting all instrument characters playing together, rainbow musical notes rising into sky, spectacular watercolor children's illustration",
      prompt: CHARACTER + "conducting all instrument characters playing together, rainbow musical notes rising into sky, spectacular watercolor children's illustration",
      emotion: "ecstatic",
    },
    {
      pageNumber: 10,
      text: "음악회 날, 관객석이 가득 찼어요. {childName}(이)가 지휘봉을 들어 올렸어요. 하나, 둘, 셋!",
      sceneDescription: "음악회 무대에서 지휘봉을 들어올리는 긴장된 장면",
      illustrationPrompt: CHARACTER + "raising a conductor's baton on a concert stage with instrument characters ready, audience watching, watercolor children's book illustration",
      prompt: CHARACTER + "raising a conductor's baton on a concert stage with instrument characters ready, audience watching, watercolor children's book illustration",
      emotion: "excited",
    },
    {
      pageNumber: 11,
      text: "공연이 끝나자 우레와 같은 박수가 쏟아졌어요. 또레미가 울먹이며 말했어요. '네 덕분이야, 고마워!'",
      sceneDescription: "공연 성공 후 박수를 받으며 기뻐하는 장면",
      illustrationPrompt: CHARACTER + "taking a bow with instrument characters on stage, audience giving standing ovation, confetti falling, watercolor children's illustration",
      prompt: CHARACTER + "taking a bow with instrument characters on stage, audience giving standing ovation, confetti falling, watercolor children's illustration",
      emotion: "proud",
    },
    {
      pageNumber: 12,
      text: "다시 다락방으로 돌아온 {childName}(이)는 오르골을 가만히 안아주었어요. 오르골에서 또레미, 둥둥이, 비올라의 하모니가 작게 울려퍼졌어요.",
      sceneDescription: "다락방에서 오르골을 안고 미소짓는 마무리 장면",
      illustrationPrompt: CHARACTER + "back in the attic hugging the music box with a gentle smile, soft golden light, watercolor children's book ending illustration",
      prompt: CHARACTER + "back in the attic hugging the music box with a gentle smile, soft golden light, watercolor children's book ending illustration",
      emotion: "content",
    },
  ],
};
