import type { Scenario } from "@/types";

const CHARACTER =
  "the same Korean child with short brown hair, wearing a light blue fluffy hooded jacket, ";

export const oceanFriends: Scenario = {
  id: "ocean-friends",
  title: "바다 친구들",
  description: "알록달록 바닷속 세계에서 물고기 친구들과 함께하는 우정 이야기",
  category: "adventure",
  educationMessage: "다르게 생겼어도 모두 소중한 친구가 될 수 있어요. 도움이 필요한 친구에게 먼저 손을 내밀어요.",
  targetAge: "3-6세",
  pageCount: 12,
  pages: [
    {
      pageNumber: 1,
      text: "{childName}(이)는 해변에서 반짝이는 조개를 주웠어요. 그 순간 파도가 살랑살랑 속삭였어요. '바닷속으로 놀러 올래?'",
      sceneDescription: "해변에서 빛나는 조개를 줍는 아이",
      illustrationPrompt: CHARACTER + "picking up a glowing seashell on a sunny beach, waves gently lapping, watercolor children's book illustration",
      prompt: CHARACTER + "picking up a glowing seashell on a sunny beach, waves gently lapping, watercolor children's book illustration",
      emotion: "curious",
    },
    {
      pageNumber: 2,
      text: "조개를 가슴에 꼭 안자, {childName}(이)의 몸이 둥둥 떠오르더니 바닷속으로 풍덩! 숨도 쉴 수 있었어요!",
      sceneDescription: "마법의 조개 덕분에 바닷속으로 들어가는 장면",
      illustrationPrompt: CHARACTER + "magically diving into a colorful underwater world holding a glowing seashell, bubbles everywhere, watercolor illustration",
      prompt: CHARACTER + "magically diving into a colorful underwater world holding a glowing seashell, bubbles everywhere, watercolor illustration",
      emotion: "amazed",
    },
    {
      pageNumber: 3,
      text: "산호초 마을에서 작은 해마 '해롱이'가 인사했어요. '안녕! 내가 바닷속을 안내해 줄게!'",
      sceneDescription: "산호초 마을에서 해마를 만나는 장면",
      illustrationPrompt: CHARACTER + "meeting a cute seahorse near colorful coral reefs underwater, friendly atmosphere, watercolor children's book style",
      prompt: CHARACTER + "meeting a cute seahorse near colorful coral reefs underwater, friendly atmosphere, watercolor children's book style",
      emotion: "excited",
    },
    {
      pageNumber: 4,
      text: "해롱이를 따라가니 거대한 해초 숲이 나타났어요. 초록 리본처럼 흔들리는 해초 사이로 햇빛이 반짝였어요.",
      sceneDescription: "거대한 해초 숲을 탐험하는 장면",
      illustrationPrompt: CHARACTER + "swimming through a magical kelp forest with a seahorse, sunbeams filtering through water, underwater watercolor illustration",
      prompt: CHARACTER + "swimming through a magical kelp forest with a seahorse, sunbeams filtering through water, underwater watercolor illustration",
      emotion: "wonder",
    },
    {
      pageNumber: 5,
      text: "해초 숲에서 거북이 할머니가 느릿느릿 헤엄치고 있었어요. '이 근처에 길 잃은 아기 물고기가 있단다. 찾아줄 수 있겠니?'",
      sceneDescription: "거북이 할머니에게 아기 물고기 이야기를 듣는 장면",
      illustrationPrompt: CHARACTER + "listening to an old wise sea turtle in a kelp forest, concerned expression, watercolor underwater illustration",
      prompt: CHARACTER + "listening to an old wise sea turtle in a kelp forest, concerned expression, watercolor underwater illustration",
      emotion: "concerned",
    },
    {
      pageNumber: 6,
      text: "{childName}(이)는 고개를 끄덕이고 해롱이와 함께 아기 물고기를 찾아 나섰어요. 깊고 어두운 바위틈도 용감하게 들여다봤어요.",
      sceneDescription: "바위틈을 살펴보며 아기 물고기를 찾는 용감한 장면",
      illustrationPrompt: CHARACTER + "bravely peeking into dark rocky crevices underwater with a seahorse, searching, watercolor children's illustration",
      prompt: CHARACTER + "bravely peeking into dark rocky crevices underwater with a seahorse, searching, watercolor children's illustration",
      emotion: "brave",
    },
    {
      pageNumber: 7,
      text: "드디어 조개 속에 숨어 있는 작고 떨리는 아기 물고기를 발견했어요! '무서웠지? 이제 괜찮아.'",
      sceneDescription: "조개 속에 숨은 아기 물고기를 발견하고 달래주는 장면",
      illustrationPrompt: CHARACTER + "gently reaching toward a small scared fish hiding in a giant clam shell, caring expression, underwater watercolor illustration",
      prompt: CHARACTER + "gently reaching toward a small scared fish hiding in a giant clam shell, caring expression, underwater watercolor illustration",
      emotion: "tender",
    },
    {
      pageNumber: 8,
      text: "아기 물고기를 데리고 산호초 마을로 돌아오니, 물고기 가족이 기뻐하며 달려왔어요. '고마워, 고마워!'",
      sceneDescription: "물고기 가족이 재회하며 감사하는 따뜻한 장면",
      illustrationPrompt: CHARACTER + "returning a baby fish to its happy family near coral reefs, joyful reunion scene, watercolor children's book illustration",
      prompt: CHARACTER + "returning a baby fish to its happy family near coral reefs, joyful reunion scene, watercolor children's book illustration",
      emotion: "happy",
    },
    {
      pageNumber: 9,
      text: "물고기 친구들이 고마움의 표시로 멋진 바다 축제를 열어 주었어요! 알록달록 물고기들이 함께 춤을 췄어요.",
      sceneDescription: "화려한 바다 축제에서 물고기들과 함께 춤추는 장면",
      illustrationPrompt: CHARACTER + "dancing with colorful fish at an underwater festival with glowing jellyfish lanterns, festive watercolor illustration",
      prompt: CHARACTER + "dancing with colorful fish at an underwater festival with glowing jellyfish lanterns, festive watercolor illustration",
      emotion: "joyful",
    },
    {
      pageNumber: 10,
      text: "문어 아저씨가 먹물로 {childName}(이)의 이름을 바다 벽에 쓰고 있었어요. '바다를 도와준 영웅이야!'",
      sceneDescription: "문어가 벽에 아이의 이름을 쓰는 재미있는 장면",
      illustrationPrompt: CHARACTER + "watching an octopus writing on a coral wall, amusing and proud expression, watercolor underwater children's illustration",
      prompt: CHARACTER + "watching an octopus writing on a coral wall, amusing and proud expression, watercolor underwater children's illustration",
      emotion: "proud",
    },
    {
      pageNumber: 11,
      text: "해롱이가 진주 팔찌를 선물해 주었어요. '언제든 이걸 차면 우리를 만날 수 있어!'",
      sceneDescription: "해마가 진주 팔찌를 선물하는 감동적인 장면",
      illustrationPrompt: CHARACTER + "receiving a pearl bracelet from a seahorse friend, sparkling underwater scene, watercolor children's book illustration",
      prompt: CHARACTER + "receiving a pearl bracelet from a seahorse friend, sparkling underwater scene, watercolor children's book illustration",
      emotion: "touched",
    },
    {
      pageNumber: 12,
      text: "파도가 {childName}(이)를 살며시 해변으로 돌려보냈어요. 손목의 진주 팔찌가 반짝이고 있었어요. '또 놀러 갈게, 바다 친구들!'",
      sceneDescription: "해변으로 돌아와 진주 팔찌를 바라보며 인사하는 마무리 장면",
      illustrationPrompt: CHARACTER + "back on the beach looking at a pearl bracelet on wrist, sunset ocean view, warm watercolor children's book ending illustration",
      prompt: CHARACTER + "back on the beach looking at a pearl bracelet on wrist, sunset ocean view, warm watercolor children's book ending illustration",
      emotion: "grateful",
    },
  ],
};
