import type { Scenario } from "@/types";

const CHARACTER =
  "the same Korean child with short brown hair, wearing a light blue fluffy hooded jacket, ";

export const superheroDay: Scenario = {
  id: "superhero-day",
  title: "슈퍼히어로의 하루",
  description: "평범한 하루에 찾아온 특별한 슈퍼파워와 따뜻한 영웅 이야기",
  category: "fantasy",
  educationMessage: "진짜 영웅은 큰 힘이 아니라 따뜻한 마음에서 시작돼요. 작은 도움도 누군가에겐 큰 힘이에요.",
  targetAge: "4-8세",
  pageCount: 12,
  pages: [
    {
      pageNumber: 1,
      text: "평범한 아침, {childName}(이)가 이를 닦는데 칫솔이 둥둥 떠올랐어요! 손을 뻗자 장난감도 떠오르고 책도 떠올랐어요!",
      sceneDescription: "아침에 물건이 둥둥 떠오르는 초능력을 발견하는 장면",
      illustrationPrompt: CHARACTER + "in a bathroom with toothbrush and objects floating in the air, surprised and amazed expression, watercolor children's book illustration",
      prompt: CHARACTER + "in a bathroom with toothbrush and objects floating in the air, surprised and amazed expression, watercolor children's book illustration",
      emotion: "surprised",
    },
    {
      pageNumber: 2,
      text: "학교에 가는 길에 빗방울이 떨어졌어요. {childName}(이)가 손을 올리자 빗방울들이 멈추고 빛나는 우산 모양이 됐어요!",
      sceneDescription: "빗방울을 멈춰 빛나는 우산을 만드는 장면",
      illustrationPrompt: CHARACTER + "stopping raindrops in mid-air forming a glowing umbrella shape, magical street scene, watercolor children's illustration",
      prompt: CHARACTER + "stopping raindrops in mid-air forming a glowing umbrella shape, magical street scene, watercolor children's illustration",
      emotion: "excited",
    },
    {
      pageNumber: 3,
      text: "횡단보도에서 할아버지가 짐을 들고 힘들어하고 있었어요. {childName}(이)가 손을 뻗자 짐이 살짝 떠올라 가벼워졌어요!",
      sceneDescription: "초능력으로 할아버지의 짐을 가볍게 해주는 장면",
      illustrationPrompt: CHARACTER + "using telekinesis to help an elderly man's heavy bags float lightly, kind expression, urban watercolor children's illustration",
      prompt: CHARACTER + "using telekinesis to help an elderly man's heavy bags float lightly, kind expression, urban watercolor children's illustration",
      emotion: "helpful",
    },
    {
      pageNumber: 4,
      text: "'고마워, 꼬마야! 마치 슈퍼히어로 같구나!' 할아버지가 웃으셨어요. {childName}(이)의 마음이 뿌듯했어요.",
      sceneDescription: "할아버지가 고마워하며 칭찬하는 장면",
      illustrationPrompt: CHARACTER + "smiling proudly as an elderly man thanks them, warm street scene, watercolor children's book illustration",
      prompt: CHARACTER + "smiling proudly as an elderly man thanks them, warm street scene, watercolor children's book illustration",
      emotion: "proud",
    },
    {
      pageNumber: 5,
      text: "학교에서 친구가 연필을 잃어버려 울고 있었어요. {childName}(이)가 집중하자 책상 밑에서 연필이 스르륵 나왔어요!",
      sceneDescription: "초능력으로 친구의 잃어버린 연필을 찾아주는 장면",
      illustrationPrompt: CHARACTER + "focusing to telekinetically find a pencil under a desk for a crying classmate, school setting, watercolor children's illustration",
      prompt: CHARACTER + "focusing to telekinetically find a pencil under a desk for a crying classmate, school setting, watercolor children's illustration",
      emotion: "caring",
    },
    {
      pageNumber: 6,
      text: "쉬는 시간에 나무 위에 올라간 고양이가 내려오지 못하고 있었어요. {childName}(이)가 살살 떠올려 안전하게 내려주었어요.",
      sceneDescription: "나무 위 고양이를 초능력으로 안전하게 내려주는 장면",
      illustrationPrompt: CHARACTER + "gently levitating a stuck cat down from a tree, schoolyard scene, magical and caring watercolor children's illustration",
      prompt: CHARACTER + "gently levitating a stuck cat down from a tree, schoolyard scene, magical and caring watercolor children's illustration",
      emotion: "gentle",
    },
    {
      pageNumber: 7,
      text: "그런데 갑자기 힘이 너무 세져서 급식 트레이가 날아가 버렸어요! 우유가 쏟아지고 난리가 났어요.",
      sceneDescription: "힘 조절 실패로 급식 트레이가 날아가는 소동 장면",
      illustrationPrompt: CHARACTER + "accidentally making lunch trays fly in a cafeteria, milk spilling, comical chaos scene, watercolor children's book illustration",
      prompt: CHARACTER + "accidentally making lunch trays fly in a cafeteria, milk spilling, comical chaos scene, watercolor children's book illustration",
      emotion: "flustered",
    },
    {
      pageNumber: 8,
      text: "{childName}(이)는 속상했어요. '힘이 있으면 뭐해, 조절을 못하는데…' 하지만 친구들이 다가와 말했어요. '괜찮아! 같이 치우자!'",
      sceneDescription: "친구들이 위로하며 함께 정리하는 따뜻한 장면",
      illustrationPrompt: CHARACTER + "looking sad while friends comfort and help clean up a messy cafeteria, supportive atmosphere, watercolor children's illustration",
      prompt: CHARACTER + "looking sad while friends comfort and help clean up a messy cafeteria, supportive atmosphere, watercolor children's illustration",
      emotion: "comforted",
    },
    {
      pageNumber: 9,
      text: "방과 후, {childName}(이)는 조용히 연습했어요. 작은 돌멩이부터 차근차근. 드디어 깃털처럼 살살 움직일 수 있게 됐어요!",
      sceneDescription: "공원에서 초능력을 조절하며 연습하는 장면",
      illustrationPrompt: CHARACTER + "carefully practicing telekinesis with small pebbles in a park, focused concentration, improving, watercolor children's book illustration",
      prompt: CHARACTER + "carefully practicing telekinesis with small pebbles in a park, focused concentration, improving, watercolor children's book illustration",
      emotion: "determined",
    },
    {
      pageNumber: 10,
      text: "집에 오니 동생이 높은 선반 위 인형을 가리키며 울고 있었어요. {childName}(이)가 살짝 손을 움직이자 인형이 사르르 내려왔어요.",
      sceneDescription: "동생을 위해 인형을 부드럽게 내려주는 장면",
      illustrationPrompt: CHARACTER + "gently floating a stuffed toy down from a high shelf for a little sibling, warm home scene, watercolor children's illustration",
      prompt: CHARACTER + "gently floating a stuffed toy down from a high shelf for a little sibling, warm home scene, watercolor children's illustration",
      emotion: "loving",
    },
    {
      pageNumber: 11,
      text: "동생이 환하게 웃으며 안겼어요. 그 순간 {childName}(이)는 깨달았어요. 진짜 슈퍼파워는 누군가를 웃게 만드는 마음이구나!",
      sceneDescription: "동생과 안으며 깨달음을 얻는 감동 장면",
      illustrationPrompt: CHARACTER + "hugging a little sibling who is smiling brightly, warm golden light, emotional moment, watercolor children's book illustration",
      prompt: CHARACTER + "hugging a little sibling who is smiling brightly, warm golden light, emotional moment, watercolor children's book illustration",
      emotion: "enlightened",
    },
    {
      pageNumber: 12,
      text: "잠자리에 든 {childName}(이)는 내일도 작은 영웅이 될 거라고 다짐했어요. 베개 옆에 놓인 손에서 작은 별빛이 반짝였어요.",
      sceneDescription: "잠자리에서 손에 별빛이 반짝이며 잠드는 마무리 장면",
      illustrationPrompt: CHARACTER + "falling asleep with a tiny star glowing on the palm, peaceful bedroom scene, warm watercolor children's book ending illustration",
      prompt: CHARACTER + "falling asleep with a tiny star glowing on the palm, peaceful bedroom scene, warm watercolor children's book ending illustration",
      emotion: "peaceful",
    },
  ],
};
