import type { Scenario } from "@/types";

const CHARACTER =
  "the same Korean child with short brown hair, wearing a light blue fluffy hooded jacket, ";

export const timeTravel: Scenario = {
  id: "time-travel",
  title: "시간 여행자",
  description: "신비한 시계탑에서 시작되는 과거와 미래를 넘나드는 여행",
  category: "science",
  educationMessage: "과거에서 배우고 미래를 꿈꾸되, 가장 소중한 건 지금 이 순간이에요.",
  targetAge: "5-9세",
  pageCount: 12,
  pages: [
    {
      pageNumber: 1,
      text: "{childName}(이)는 동네 골목에서 아무도 모르는 낡은 시계탑을 발견했어요. 시계가 거꾸로 돌고 있었지요!",
      sceneDescription: "골목에서 거꾸로 도는 낡은 시계탑을 발견하는 장면",
      illustrationPrompt: CHARACTER + "discovering an old clock tower with hands spinning backwards in a mysterious alley, twilight atmosphere, watercolor children's book illustration",
      prompt: CHARACTER + "discovering an old clock tower with hands spinning backwards in a mysterious alley, twilight atmosphere, watercolor children's book illustration",
      emotion: "curious",
    },
    {
      pageNumber: 2,
      text: "시계탑 문을 열자 안에는 빛나는 모래시계가 있었어요. 모래시계를 뒤집자 세상이 빙글빙글 돌았어요!",
      sceneDescription: "빛나는 모래시계를 뒤집는 순간의 마법적 장면",
      illustrationPrompt: CHARACTER + "flipping a glowing hourglass inside a clock tower, swirling time vortex forming, magical watercolor children's illustration",
      prompt: CHARACTER + "flipping a glowing hourglass inside a clock tower, swirling time vortex forming, magical watercolor children's illustration",
      emotion: "amazed",
    },
    {
      pageNumber: 3,
      text: "눈을 떠보니 옛날 마을이었어요! 한복을 입은 아이들이 제기차기를 하고 있었어요. '같이 놀래?'",
      sceneDescription: "조선시대 마을에서 한복 입은 아이들을 만나는 장면",
      illustrationPrompt: CHARACTER + "arriving in a traditional Korean village with children in hanbok playing jegichagi, historical and warm atmosphere, watercolor children's illustration",
      prompt: CHARACTER + "arriving in a traditional Korean village with children in hanbok playing jegichagi, historical and warm atmosphere, watercolor children's illustration",
      emotion: "excited",
    },
    {
      pageNumber: 4,
      text: "제기차기는 처음이었지만 금방 배웠어요! 옛날 친구들이 맛있는 떡도 나눠주었어요.",
      sceneDescription: "옛날 아이들과 제기차기하며 떡을 나눠 먹는 장면",
      illustrationPrompt: CHARACTER + "playing jegichagi with Korean children in historical village, eating rice cakes together, warm watercolor children's book illustration",
      prompt: CHARACTER + "playing jegichagi with Korean children in historical village, eating rice cakes together, warm watercolor children's book illustration",
      emotion: "joyful",
    },
    {
      pageNumber: 5,
      text: "모래시계를 다시 뒤집자 이번에는 먼 미래로! 하늘에 자동차가 날아다니고 로봇이 인사해요.",
      sceneDescription: "미래 도시에 도착해 하늘을 나는 자동차를 보는 장면",
      illustrationPrompt: CHARACTER + "standing in a futuristic city with flying cars and friendly robots, amazed expression, colorful sci-fi watercolor children's illustration",
      prompt: CHARACTER + "standing in a futuristic city with flying cars and friendly robots, amazed expression, colorful sci-fi watercolor children's illustration",
      emotion: "wonder",
    },
    {
      pageNumber: 6,
      text: "미래의 도서관에서는 책이 홀로그램으로 떠올랐어요. {childName}(이)가 손을 뻗자 공룡이 눈앞에서 움직였어요!",
      sceneDescription: "홀로그램 도서관에서 공룡이 튀어나오는 장면",
      illustrationPrompt: CHARACTER + "reaching out to a holographic dinosaur in a futuristic library, amazed expression, glowing holograms, watercolor children's illustration",
      prompt: CHARACTER + "reaching out to a holographic dinosaur in a futuristic library, amazed expression, glowing holograms, watercolor children's illustration",
      emotion: "fascinated",
    },
    {
      pageNumber: 7,
      text: "그런데 갑자기 모래시계의 빛이 깜빡거렸어요! 모래가 거의 다 떨어지고 있었어요. '빨리 돌아가야 해!'",
      sceneDescription: "모래시계의 모래가 거의 다 떨어진 긴박한 장면",
      illustrationPrompt: CHARACTER + "looking worried at a flickering hourglass with sand almost gone, urgent atmosphere, watercolor children's book illustration",
      prompt: CHARACTER + "looking worried at a flickering hourglass with sand almost gone, urgent atmosphere, watercolor children's book illustration",
      emotion: "worried",
    },
    {
      pageNumber: 8,
      text: "미래의 로봇 친구 '틱톡'이 에너지 젤리를 건네주었어요. '이걸 모래시계에 넣어봐!'",
      sceneDescription: "로봇 친구가 에너지 젤리를 건네주는 장면",
      illustrationPrompt: CHARACTER + "receiving a glowing energy jelly from a friendly robot in a futuristic setting, hopeful moment, watercolor children's illustration",
      prompt: CHARACTER + "receiving a glowing energy jelly from a friendly robot in a futuristic setting, hopeful moment, watercolor children's illustration",
      emotion: "hopeful",
    },
    {
      pageNumber: 9,
      text: "에너지 젤리를 넣자 모래시계가 다시 환하게 빛났어요! 시간의 소용돌이가 {childName}(이)를 감쌌어요.",
      sceneDescription: "모래시계가 부활하며 시간 소용돌이에 감싸이는 장면",
      illustrationPrompt: CHARACTER + "putting energy jelly into the hourglass which glows brightly, time vortex swirling, magical watercolor children's illustration",
      prompt: CHARACTER + "putting energy jelly into the hourglass which glows brightly, time vortex swirling, magical watercolor children's illustration",
      emotion: "relieved",
    },
    {
      pageNumber: 10,
      text: "무사히 시계탑으로 돌아왔어요! 주머니에서 옛날 제기와 미래 에너지 젤리 하나가 나왔어요.",
      sceneDescription: "시계탑으로 돌아와 여행의 증거물을 발견하는 장면",
      illustrationPrompt: CHARACTER + "back in the clock tower holding a traditional jegi and a futuristic energy jelly, smiling, watercolor children's book illustration",
      prompt: CHARACTER + "back in the clock tower holding a traditional jegi and a futuristic energy jelly, smiling, watercolor children's book illustration",
      emotion: "satisfied",
    },
    {
      pageNumber: 11,
      text: "시계탑의 시계가 다시 똑딱똑딱 정상으로 돌기 시작했어요. 모래시계 위에 새 글자가 떠올랐어요. '가장 좋은 시간은 바로 지금!'",
      sceneDescription: "시계탑이 정상화되고 모래시계에 메시지가 뜨는 장면",
      illustrationPrompt: CHARACTER + "watching the clock tower normalize while a glowing message appears on the hourglass, peaceful moment, watercolor children's illustration",
      prompt: CHARACTER + "watching the clock tower normalize while a glowing message appears on the hourglass, peaceful moment, watercolor children's illustration",
      emotion: "thoughtful",
    },
    {
      pageNumber: 12,
      text: "시계탑을 나온 {childName}(이)는 노을빛 하늘을 올려다보며 활짝 웃었어요. 오늘 하루가 세상에서 가장 특별한 시간이었어요!",
      sceneDescription: "시계탑 밖에서 노을을 바라보며 미소짓는 마무리 장면",
      illustrationPrompt: CHARACTER + "walking out of the clock tower into a beautiful sunset, peaceful and happy smile, watercolor children's book ending illustration",
      prompt: CHARACTER + "walking out of the clock tower into a beautiful sunset, peaceful and happy smile, watercolor children's book ending illustration",
      emotion: "happy",
    },
  ],
};
